image: docker:latest

services:

- docker: dind

stages:

- build

- deploy

variables:

# Common

AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
AWS_REGION: $AWS_REGION
S3_BUCKET_NAME: $S3_BUCKET_NAME
CDN_DISTRIBUTION_ID: $CDN_DISTRIBUTION_ID

cache:

key: $CI_COMMIT_REF_SLUG

paths:

- node_modules/